# Generated by Django 5.2.11 on 2026-03-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_navigation_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='navigationconfig',
            name='menu_json',
            field=models.TextField(help_text='JSON válido con la estructura de menu por rol'),
        ),
    ]
