# Generated by Django 5.2.11 on 2026-03-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_actionaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationconfig',
            name='menu_json',
            field=models.TextField(help_text='JSON valido con la estructura de menu por rol'),
        ),
    ]
